### ISSUE TITLE
Infra Todo

### ISSUE THREAD

**Issue by jamesward** [EffectOrientedProgramming/book#313]
- [x] Speed up time for ToRun and alter output to make it wall clock again
- [x] Parallel mdoc processing
- [x] Test output includes the ToTest and shouldn't
- [x] Put examples in packages
- [x] ZIOAppDefault doesn't output an effect's result (different than manuscript)
- [x] Ordering of regular code snippets and run zios
- [x] Separate code from output in manuscript
- [x] `.debug` outputs stacktraces for failures which is verbose
- [x] Remove `^` lines from compile error mdocs

**Comment by jamesward** [comment]
We can avoid doing a `.debug` on failures, like: https://github.com/EffectOrientedProgramming/book/commit/a95401e05c40e25aa4cec462d6e4836c6952e8e8

I think that is a better approach than trying to muck with the output as that doesn't do anything for the examples.

**Comment by jamesward** [comment]
Also I think that to address the result not outputting in examples, we should use `.debug` instead of manually including the result in mdoc / manuscript.

**Comment by swoogles** [comment]
Observation - searching for ^'s in the generated output is actually pretty useful for finding places where our more brittle error stripping has failed. Something to consider before we strip them out.
